laravel/routes/admin.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/


Route::get('/', 'BackEnd\MainController@index');


// Route::group(['middleware' => ['auth', 'role:super-admin, sub-admin']], function () {


Route::group(['namespace' => 'BackEnd'], function () { 

Route::post('/accounts/search', 'AccountsResource@search');
Route::resource('/accounts', 'AccountsResource');

Route::resource('/categories', 'CategoriesResource');

Route::post('/products/search', 'ProductsResource@search');
Route::post('/products/status', 'ProductsResource@updateStatus')->name('products.status');	
Route::resource('/products', 'ProductsResource');

Route::get('/rental-requests/{page?}', 'RentalRequestsResource@index');
Route::post('/rental-requests/status', 'RentalRequestsResource@updateStatus');	
Route::resource('/rental-requests/', 'RentalRequestsResource')->except('index');


Route::post('/transactions/update-start-end', 'TransactionsResource@updateStartEnd');
Route::get('/transactions/{page?}', 'TransactionsResource@index');
Route::post('/transactions/status', 'TransactionsResource@updateStatus');
Route::resource('/transactions/', 'TransactionsResource')->except('index');

});

// });

laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::get('', function () {
   
});

Route::get('/', 'HomeController@index');


Route::group(['middleware' => ['auth','role:super-admin|sub-admin']], function () {

Route::get('/mail', 'HomeController@sendEmail');

Route::get('/', 'HomeController@index');

Route::group(['namespace' => 'AdminPanel'], function () { 

Route::post('/accounts/search', 'AccountsResource@search');
Route::resource('/accounts', 'AccountsResource');


Route::post('/categories/search', 'CategoriesResource@search');
Route::resource('/categories', 'CategoriesResource');


Route::post('/products/search', 'ProductsResource@search');
Route::post('/products/status', 'ProductsResource@updateStatus')->name('products.status');	
Route::resource('/products', 'ProductsResource');

Route::post('/rental-requests/update-approved-qty', 'RentalRequestsResource@updateApprovedQty');

Route::get('/rental-requests/{page?}', 'RentalRequestsResource@index');
Route::post('/rental-requests/remove-record', 'RentalRequestsResource@removeRecord');
Route::post('/rental-requests/status', 'RentalRequestsResource@updateStatus');	
Route::resource('/rental-requests/', 'RentalRequestsResource')->except('index');
Route::post('/rental-requests/update-start-end', 'RentalRequestsResource@updateStartEnd');

Route::post('/transactions/deny-request', 'TransactionsResource@denyRequest');
Route::post('/transactions/update-start-end', 'TransactionsResource@updateStartEnd');
Route::get('/transactions/{page?}', 'TransactionsResource@index');
Route::resource('/transactions/', 'TransactionsResource')->except('index');

});


});

laravel/resources/views/partials/card-header.blade.php
  <div class="row page-title-header">
  	<div class="col-12">
  		<div class="page-header">
  			<h4 class="page-title" style="white-space: nowrap;"></h4>
  			<div class="quick-link-wrapper w-100 d-md-flex flex-md-wrap">

  				<h4>{{strtoupper($title)}}</h4>              

  			</div>
  		</div>
  	</div>

  </div>

laravel/resources/views/partials/footer.blade.php
<footer class="footer">
  <div class="container-fluid clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2019 <a href="Javascript:void(0)" target="_blank">Your Boutique</a>. All rights reserved.</span>
  </div>
</footer>

laravel/resources/views/partials/navbar.blade.php
<nav class="navbar default-layout col-lg-12 col-12 p-0 fixed-top d-flex flex-row">
  <div class="text-center navbar-brand-wrapper d-flex align-items-top justify-content-center">
    <a class="navbar-brand brand-logo" href="/">
      <img src="{{asset('assets/images/logo-your-boutique.png')}}" alt="logo" /> </a>
      <a class="navbar-brand brand-logo-mini" href="/">
        <img src="{{asset('assets/images/logo-mini.svg')}}" alt="logo" /> </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
       
       
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown">
           {{--  <a class="nav-link count-indicator" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
              <i class="mdi mdi-bell-outline"></i>
              <span class="count">7</span>
            </a> --}}
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="messageDropdown">
              <a class="dropdown-item py-3">
                <p class="mb-0 font-weight-medium float-left">You have 7 unread mails </p>
                <span class="badge badge-pill badge-primary float-right">View all</span>
              </a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item preview-item">
                <div class="preview-thumbnail">
                  <img src="{{asset('assets/images/faces/face10.jpg')}}" alt="image" class="img-sm profile-pic"> </div>
                  <div class="preview-item-content flex-grow py-2">
                    <p class="preview-subject ellipsis font-weight-medium text-dark">Marian Garner </p>
                    <p class="font-weight-light small-text"> The meeting is cancelled </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item">
                  <div class="preview-thumbnail">
                    <img src="{{asset('assets/images/faces/face12.jpg')}}" alt="image" class="img-sm profile-pic"> </div>
                    <div class="preview-item-content flex-grow py-2">
                      <p class="preview-subject ellipsis font-weight-medium text-dark">David Grey </p>
                      <p class="font-weight-light small-text"> The meeting is cancelled </p>
                    </div>
                  </a>
                  <a class="dropdown-item preview-item">
                    <div class="preview-thumbnail">
                      <img src="{{asset('assets/images/faces/face1.jpg')}}" alt="image" class="img-sm profile-pic"> </div>
                      <div class="preview-item-content flex-grow py-2">
                        <p class="preview-subject ellipsis font-weight-medium text-dark">Travis Jenkins </p>
                        <p class="font-weight-light small-text"> The meeting is cancelled </p>
                      </div>
                    </a>
                  </div>
                </li>
     <!--  <li class="nav-item dropdown">
        <a class="nav-link count-indicator" id="notificationDropdown" href="#" data-toggle="dropdown">
          <i class="mdi mdi-email-outline"></i>
          <span class="count bg-success">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="notificationDropdown">
          <a class="dropdown-item py-3 border-bottom">
            <p class="mb-0 font-weight-medium float-left">You have 4 new notifications </p>
            <span class="badge badge-pill badge-primary float-right">View all</span>
          </a>
          <a class="dropdown-item preview-item py-3">
            <div class="preview-thumbnail">
              <i class="mdi mdi-alert m-auto text-primary"></i>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal text-dark mb-1">Application Error</h6>
              <p class="font-weight-light small-text mb-0"> Just now </p>
            </div>
          </a>
          <a class="dropdown-item preview-item py-3">
            <div class="preview-thumbnail">
              <i class="mdi mdi-settings m-auto text-primary"></i>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal text-dark mb-1">Settings</h6>
              <p class="font-weight-light small-text mb-0"> Private message </p>
            </div>
          </a>
          <a class="dropdown-item preview-item py-3">
            <div class="preview-thumbnail">
              <i class="mdi mdi-airballoon m-auto text-primary"></i>
            </div>
            <div class="preview-item-content">
              <h6 class="preview-subject font-weight-normal text-dark mb-1">New user registration</h6>
              <p class="font-weight-light small-text mb-0"> 2 days ago </p>
            </div>
          </a>
        </div>
      </li> -->
      <li class="nav-item dropdown d-none d-xl-inline-block user-dropdown">
        <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
          <img class="img-xs rounded-circle" src="{{asset('assets/images/faces-clipart/pic-1.png')}}" alt="Profile image"> </a>
          <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
            <div class="dropdown-header text-center">
              <img class="img-sm  rounded-circle" src="{{asset('assets/images/faces-clipart/pic-1.png')}}" alt="Profile image">
              <p class="mb-1 mt-3 font-weight-semibold">{{ isset(Auth::user()->name) ? Auth::user()->name : ''}}</p>
              <p class="font-weight-light text-muted mb-0">{{ isset(Auth::user()->email) ? Auth::user()->email : ''}}</p>

            </div>
            <a class="dropdown-item" href="/accounts/{{ isset(Auth::user()->id) ? Auth::user()->id : ''}}/edit" target="_blank">My Profile</a>
           <a class="dropdown-item" href="{{ route('logout') }}"  onclick="event.preventDefault();
            document.getElementById('logout-form').submit();">Sign Out<i class="dropdown-item-icon ti-power-off"></i></a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
            </form>
          </div>
        </li>
      </ul>
      <button class="navbar-toggler navbar-toggler-right d-lg-none align-self-center" type="button" data-toggle="offcanvas">
        <span class="mdi mdi-menu"></span>
      </button>
    </div>
  </nav>

laravel/resources/views/partials/product-details.blade.php
<table>
  <tbody>
    <tr>
      <td>INITIAL RATE:</td>
      <td>{{$product->SucceedingDaysRateMutated}}</td>
    </tr>
    <tr>
      <td>SUCC. DAYS RATE:</td>
      <td>{{$product->succeedingDaysRateMutated}}</td>
   </tr>
   <tr>
    <td>CATEGORY:</td>
    <td>
      {{ucfirst($product->category)}}
    </td>
  </tr>
</tbody>
</table>

laravel/resources/views/partials/search-form.blade.php
  <form method="POST" id="search" action="{{$route}}">
    @csrf
    <div class="col-lg-12">
     <div class="row">
       <div class="col-lg-4">
        <div class="form-group">
          <div class="input-group">
            <input type="text" class="form-control" name="search" placeholder="Search" aria-label="Search" aria-describedby="colored-addon3" autofocus>
            <div class="input-group-append bg-secondary border-primary">
              <span class="input-group-text bg-transparent">
               <a style="cursor: pointer;" onclick="document.querySelector('#search').submit()">
                <i class="fa fa-search "></i>
              </a>
            </span>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-3">
     <div class="form-group">
      <select class="form-control form-control-lg" name="key" required>

        @foreach($searchKey as $key) 
             <option  value="{{$key['value']}}" @if($loop->first) selected @endif>{{$key['text']}}</option>
        @endforeach
  
      </select>
    </div>
  </div>
</div>
</div>
</form>

laravel/resources/views/partials/show-edit-product.blade.php
<a href="{{route('products.show', $product_id)}}" target="_blank" class="custom-link-text">
	{{$product_id}}
</a>
<a href="{{route('products.edit', $product_id)}}" target="_blank"> &nbsp;<i class="fa fa-edit text-dark"></i></a>

laravel/resources/views/partials/show-edit-user.blade.php
<a href="{{route('accounts.show', $user_id)}}" target="_blank" class="custom-link-text">
	{{$user_id}}
</a>
<a href="{{route('accounts.edit', $user_id)}}" target="_blank"> &nbsp;<i class="fa fa-edit text-dark"></i></a>

laravel/resources/views/partials/sidebar.blade.php
<nav class="sidebar sidebar-offcanvas pb-5" id="sidebar">


  <ul class="nav navmain">
 <li class="nav-item nav-profile">
      <a href="#" class="nav-link">
        <div class="profile-image">
          <img class="img-xs rounded-circle" src="{{asset('assets/images/faces-clipart/pic-1.png')}}" alt="profile image">
          <div class="dot-indicator bg-success"></div>
        </div>
        <div class="text-wrapper">
          <p class="profile-name">{{ isset(Auth::user()->name) ? Auth::user()->name : ''}}</p>
          <p class="designation">{{   isset(Auth::user()->name) ? Auth::user()->getRoleNames()->first() : ''}}</p>
        </div>
      </a>
    </li>
    <li class="nav-item nav-category">Main Menu</li>

    <li class="nav-item">
      <a class="nav-link" href="/accounts">
        <i class="menu-icon typcn typcn-document-text"></i>
        <span class="menu-title">Accounts</span>
      </a>
    </li>

    <li class="nav-item">
      <a class="nav-link" href="/products">
        <i class="menu-icon typcn typcn-document-text"></i>
        <span class="menu-title">Products</span>
      </a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/categories">
        <i class="menu-icon typcn typcn-document-text"></i>
        <span class="menu-title">Product Categories</span>
      </a>
    </li>

  <!--   <li class="nav-item">
      <a class="nav-link" href="discount">
        <i class="menu-icon typcn typcn-document-text"></i>
        <span class="menu-title">Product Discount</span>
      </a>
    </li>
  -->
  <li class="nav-item nav-category">Rental Request</li>

  <li class="nav-item">
    <a class="nav-link" href="/rental-requests/pending-request">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">Pending request</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="/rental-requests/accepted-request">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">Accepted request</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="/rental-requests/customer-cancel-request">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">Customer Cancel Request</span>
    </a>
  </li>



  <li class="nav-item">
    <a class="nav-link" href="/rental-requests/cancelled-request">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">Cancelled request</span>
    </a>
  </li>


  <li class="nav-item nav-category">Transactions</li>

  <li class="nav-item">
    <a class="nav-link" href="/transactions/on-going">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">On going</span>
    </a>
  </li>

  <li class="nav-item">
    <a class="nav-link" href="/transactions/completed">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">Completed</span>
    </a>
  </li>


  <li class="nav-item">
    <a class="nav-link" href="/transactions/void-refunded">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">Void & Refunded</span>
    </a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/transactions/remove-record">
      <i class="menu-icon typcn typcn-document-text"></i>
      <span class="menu-title">Remove Records</span>
    </a>
  </li>
</ul>
</nav>

<style>
  .navmain {
position: fixed;
 overflow: hidden;
    max-height: 100vh;
}
  .navmain:hover{
    overflow-y: scroll;
  }
</style>

laravel/resources/views/partials/success-error-notification-tiny.blade.php
 <!-- custom errors and success notification -->



 @if(session('success'))
 <div class="col-lg-12">
    <code>{{session('success')}}</code>
</div>
@endif


@if($message = Session::get('error'))
<div class="col-lg-12">
    <div class="code">{{$message}}</code>

</div>
@endif


@if(count($errors) > 0 ) 
<div class="col-lg-12">
    @foreach($errors->all() as $error)
    <code>{{$error}}</code>
    @endforeach
</div>
@endif

laravel/resources/views/partials/success-error-notification.blade.php
 <!-- custom errors and success notification -->



 @if(session('success'))
 <div class="col-lg-12">
    <div class="alert alert-success">{{session('success')}}</div>
</div>
@endif


@if($message = Session::get('error'))
<div class="col-lg-12">
    <div class="alert alert-danger">{{$message}}</div>

</div>
@endif


@if(count($errors) > 0 ) 
<div class="col-lg-12">
    @foreach($errors->all() as $error)
    <div class="alert alert-danger">{{$error}}</div>
    @endforeach
</div>
@endif

laravel/resources/views/partials/transanction-user-product.blade.php
<table>
  <tbody>
    <tr>
      <td>TRANSACTION ID:</td>
      <td> {{$transaction_id}}</td>
    </tr>
    <tr>
      <td>CUSTOMER ID:</td>
      <td>
       @include('partials.show-edit-user', ['user_id' => $customer_id])
     </td>
   </tr>
   <tr>
    <td>PRODUCT ID:</td>
    <td>
      @include('partials.show-edit-product', ['product_id' => $product_id])
    </td>
  </tr>
</tbody>
</table>