laravel/routes/admin.php
<?php

use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "api" middleware group. Enjoy building your API!
|
*/


Route::get('/', 'BackEnd\MainController@index');


// Route::group(['middleware' => ['auth', 'role:super-admin, sub-admin']], function () {


Route::group(['namespace' => 'BackEnd'], function () { 

Route::post('/accounts/search', 'AccountsResource@search');
Route::resource('/accounts', 'AccountsResource');

Route::resource('/categories', 'CategoriesResource');

Route::post('/products/search', 'ProductsResource@search');
Route::post('/products/status', 'ProductsResource@updateStatus')->name('products.status');	
Route::resource('/products', 'ProductsResource');

Route::get('/rental-requests/{page?}', 'RentalRequestsResource@index');
Route::post('/rental-requests/status', 'RentalRequestsResource@updateStatus');	
Route::resource('/rental-requests/', 'RentalRequestsResource')->except('index');


Route::post('/transactions/update-start-end', 'TransactionsResource@updateStartEnd');
Route::get('/transactions/{page?}', 'TransactionsResource@index');
Route::post('/transactions/status', 'TransactionsResource@updateStatus');
Route::resource('/transactions/', 'TransactionsResource')->except('index');

});

// });

laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();


Route::get('', function () {
   
});

Route::get('/', 'HomeController@index');


Route::group(['middleware' => ['auth','role:super-admin|sub-admin']], function () {

Route::get('/mail', 'HomeController@sendEmail');

Route::get('/', 'HomeController@index');

Route::group(['namespace' => 'AdminPanel'], function () { 

Route::post('/accounts/search', 'AccountsResource@search');
Route::resource('/accounts', 'AccountsResource');


Route::post('/categories/search', 'CategoriesResource@search');
Route::resource('/categories', 'CategoriesResource');


Route::post('/products/search', 'ProductsResource@search');
Route::post('/products/status', 'ProductsResource@updateStatus')->name('products.status');	
Route::resource('/products', 'ProductsResource');

Route::post('/rental-requests/update-approved-qty', 'RentalRequestsResource@updateApprovedQty');

Route::get('/rental-requests/{page?}', 'RentalRequestsResource@index');
Route::post('/rental-requests/remove-record', 'RentalRequestsResource@removeRecord');
Route::post('/rental-requests/status', 'RentalRequestsResource@updateStatus');	
Route::resource('/rental-requests/', 'RentalRequestsResource')->except('index');
Route::post('/rental-requests/update-start-end', 'RentalRequestsResource@updateStartEnd');

Route::post('/transactions/deny-request', 'TransactionsResource@denyRequest');
Route::post('/transactions/update-start-end', 'TransactionsResource@updateStartEnd');
Route::get('/transactions/{page?}', 'TransactionsResource@index');
Route::resource('/transactions/', 'TransactionsResource')->except('index');

});


});

laravel/app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Category;
use App\Models\Image;
use Cviebrock\EloquentSluggable\Sluggable;
use Illuminate\Database\Eloquent\Model;
use App\User;

class Product extends Model
{
	
	use Sluggable;

	protected $table = 'products';

	protected $fillable = ['title', 'serial', 'description', 'slug','initial_rate', 'status','category_id', 'succeeding_days_rate'];

	protected $attributes = [
		'initial_rate' => 0
	];

	public function sluggable()
	{
		return [
			'slug' => [
				'source' => 'title'
			]
		];
	}     


	public function category()
	{
		return $this->belongsTo(Category::class, 'category_id');
	}  

	// 	public function images()
	// {
	// 	return $this->hasMany(Image::class, 'product_id');
	// }   

	// public function category()
	// {
	// 	return $this->belongsTo(category::class, 'category_id');
	// }     

	public function getDailyRateAttribute($value) {

		return number_format($value, 2);

	}


	public function setDailyRateAttribute($value) {

		$newVal = preg_replace("/[A-Za-z\,\s]/", '', $value);

		$this->attributes['initial_rate'] = $newVal;

	}

	public function getImagePathAttribute() {


		if(count($this->images)) {
			return  "/". $this->images()->value('directory_name') . '/'. $this->images()->value('file_name');
		}

	}

	public function images()
	{
		return $this->morphMany(Image::class, 'imageable');
	}


	// public function cart()
 //    {
 //        return $this->belongsToMany(User::class, 'carts', 'product_id', 'user_id');
 //    } 

	public function getInitialRateMutatedAttribute() {

		$result = '';

		if($this->initial_rate == null || $this->initial_rate == '') {

			$result = 'P 0.00';

		} else {

			$result = 'P ' . number_format($this->initial_rate, 2); 

		}

		return $result;

	}

	public function getSucceedingDaysRateMutatedAttribute() {

		$result = '';

		if($this->succeeding_days_rate == null || $this->succeeding_days_rate == '') {

			$result = 'P 0.00';

		} else {

			$result = 'P ' . number_format($this->succeeding_days_rate, 2); 

		}

		return $result;

	}

}

laravel/app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Controllers\Controller;
use App\Http\Resources\ProductResource;
use App\Http\Resources\ProductsCollection;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Request as Url;
use Request as Req;
use Symfony\Component\HttpFoundation\Response;
class ProductController extends Controller
{

 private $model; 

 public function  __construct() {

  $this->model = new Product;  

} 


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        if(Req::has('Authorization') || Req::header('Authorization')) {
            $user = Auth::guard('api')->user();
        }
        try {
          $category = (Url::get('category') != 'null' && Url::get('category') != '') ? Url::get('category') : null;
           $value = Url::get('value');

          switch (true) {

            case ($category != null):
            $model =  $this->model::whereHas('category', function($q) use 
                ($category) {
                $q->where('name', $category);
            })->orderBy('created_at', 'desc')
            ->whereStatus(1)
            ->paginate(15);
            break;
           
            case ($value != 'null'):
            $model =  $this->model::where('title', 'LIKE', '%' . $value . '%')
            ->orderBy('created_at', 'desc')
            ->whereStatus(1)
            ->paginate(15);
            break;

            default:
            $model = $this->model->orderBy('created_at', 'desc')
            ->whereStatus(1)
            ->paginate(15);
        }
        $modelResource = ProductsCollection::collection($model);
        $response = [
            'pagination' => [
              'total' => $model->total(),
                'per_page' => $model->perPage(),
                'current_page' =>  $model->currentPage(),
                'last_page' =>  $model->lastPage(),
                "page_url" => "products?page=",
                'from' => $model->firstItem()
          ],
          'data' =>  $modelResource,
      ];
      return response()->json($response, Response::HTTP_OK);
  } catch(\Exception $e) {
   return response(['error' => $e->getMessage()], Response::HTTP_BAD_REQUEST);
}

}

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $model = Product::whereSlug($id)->first();
        $model =  new ProductResource($model);
        return response()->json($model, Response::HTTP_OK);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function newArrivals()
    {
        $response = ProductsCollection::
        collection($this->model->orderBy('created_at', 'desc')->take(10)
            ->whereStatus(1)
            ->get());
        return response()->json($response, Response::HTTP_OK);
    }

    public function categories()
    {
     $data = Category::pluck('name');
     return response()->json($data, Response::HTTP_OK);
 }

 //   public function singleProductDetails($slug) {
 // return response()->json($slug, Response::HTTP_OK);

 //   }



}

laravel/resources/views/pages/products/create.blade.php
	@extends('template.main')

@section('body')

@include('partials.card-header', ['title' => 'Add Product'])

@include('partials.success-error-notification')

<div class="row">
	<div class="col-lg-12 d-flex justify-center ">
		<div class="col-lg-6 grid-margin stretch-card offset-lg-3">
			<div class="card">
				<div class="card-body">

					<form class="forms-sample"  action="{{route('products.store')}}" method="POST" enctype="multipart/form-data">
						@csrf
						<div class="form-group">
							<label >Product title</label>
							<input type="text" name="product[title]" class="form-control" required>
						</div>
						<div class="form-group">
							<label >Product serial</label>
							<input type="text" class="form-control" name="product[serial]">
						</div>


						<div class="form-group">
							<label>Status</label>
							<select class="form-control" name="product[status]">
								<option value="1" >Available</option>
								<option value="0" selected>Not available</option>
							</select>
						</div>

						<div class="form-group">
							<label>Initial rate</label>
							<div class="input-group">
								<div class="input-group-prepend bg-secondary border-primary">
									<span class="input-group-text bg-transparent text-black">P</span>
								</div>
								<input required type="text" class="form-control"  name="product[initial_rate]" aria-label="Amount (to the nearest dollar)">
							</div>
						</div>

						<div class="form-group">
							<label>Succeeding Days Rate</label>
							<div class="input-group">
								<div class="input-group-prepend bg-secondary border-primary">
									<span class="input-group-text bg-transparent text-black">P</span>
								</div>
								<input required type="text" class="form-control"  name="product[succeeding_days_rate]" aria-label="Amount (to the nearest dollar)">
							</div>
						</div>

						<div class="form-group">
							<label>Category</label>
							<select class="form-control" name="product[category_id]">
								@foreach($categories as $category)
								<option value="{{$category->id}}">{{$category->name}}</option>
								@endforeach
							</select>
						</div>



						<div class="form-group">
							<label>Image upload</label>
							<div class="input-group">
								<span class="input-group-btn bg-secondary">
									<span class="btn btn-default btn-file">
										Browse… <input type="file" name="image" required id="imgInp">
									</span>
								</span>
								<input type="text"  class="form-control bg-transparent"  readonly>
							</div>
							<img id='img-upload'/>
						</div>


						<div class="form-group">
							<label>Notes</label>
							<textarea class="form-control" name="product[description]" rows="2"></textarea>
						</div>

						<div class="mt-3">
						<button type="submit" class="btn btn-primary mr-2">Submit</button>
						<a href="{{route('products.index')}}" class="btn btn-light">Cancel</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

laravel/resources/views/pages/products/edit.blade.php
@extends('template.main')

@section('body')

 @include('partials.card-header', ['title' => 'Edit Product'])

@include('partials.success-error-notification')

<div class="row">
	<div class="col-lg-12 d-flex justify-center ">
		<div class="col-lg-6 grid-margin stretch-card offset-lg-3">
			<div class="card">
				<div class="card-body">

					<form class="forms-sample"  action="{{route('products.update', $product->id)}}" method="POST" enctype="multipart/form-data">
						@method('PUT')
						@csrf
						

						<div class="form-group">
							<label>Product ID</label>
							<input type="text" readonly  value="{{$product->id}}" class="form-control" >
						</div>
						<div class="form-group">
							<label >Product Title</label>
							<input type="text" name="product[title]" class="form-control"  value="{{$product->title}}">
						</div>
						<div class="form-group">
							<label >Product Serial</label>
							<input type="text" class="form-control" name="product[serial]"  value="{{$product->serial}}">
						</div>


						<div class="form-group">
							<label>Status</label>
							<select class="form-control" name="product[status]">
								@if($product->status)
								<option value="1" selected>Available</option>
								<option value="0">Not available</option>
								@else
								<option value="1">Available</option>
								<option value="0"selected>Not available</option>
								@endif
							</select>
						</div>

						 <div class="form-group">
						 	<label>Initial rate</label>
                          <div class="input-group">
                            <div class="input-group-prepend bg-secondary border-primary">
                              <span class="input-group-text bg-transparent text-black">P</span>
                            </div>
                            <input type="text" class="form-control" value="{{$product->initial_rate}}" name="product[initial_rate]" aria-label="Amount (to the nearest dollar)">
                          </div>
                        </div>


						<div class="form-group">
							<label>Succeeding Days Rate</label>
							<div class="input-group">
								<div class="input-group-prepend bg-secondary border-primary">
									<span class="input-group-text bg-transparent text-black">P</span>
								</div>
								<input type="text" class="form-control"  name="product[succeeding_days_rate]"
								value="{{$product->succeeding_days_rate}}"
								 aria-label="Amount (to the nearest dollar)">
							</div>
						</div>


						<div class="form-group">
							<label>Product Category</label>
							<select class="form-control" name="product[category_id]" >
								@foreach($categories as $category)

								@if($product->category()->value('id') == $category->id)
								<option value="{{$category->id}}" selected>{{$category->name}}</option>
								@else
								<option value="{{$category->id}}">{{$category->name}}</option>
								@endif

								@endforeach
							</select>
						</div>
						
						<div class="form-group">
							<label>Image upload</label>
							<div class="input-group">
								<span class="input-group-btn bg-secondary">
									<span class="btn btn-default btn-file">
										Browse… <input type="file" name="image" id="imgInp">
									</span>
								</span>
								<input type="text"  class="form-control bg-transparent"  readonly>
							</div>
							<img id='img-upload'/>
						</div>

						<div class="form-group">
							<label>Notes</label>
							<textarea class="form-control" name="product[description]" rows="2">{{$product->description}}</textarea>
						</div>

						<div class="mt-3">
						<button type="submit" class="btn btn-primary mr-2">Submit</button>
						<a href="{{route('products.index')}}" class="btn btn-light">Cancel</a>
					</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

laravel/resources/views/pages/products/index.blade.php
  @extends('template.main')

  @section('body')

  @include('partials.card-header', ['title' => 'Product Lists'])

  @include('partials.success-error-notification')
  
  @include('partials.search-form', [ 'route' => '/products/search', 
  'searchKey' => [
  ['value' => 'serial', 'text' => 'SERIAL'],
  ['value' => 'id', 'text' => 'PRODUCT ID'],
  ['value' => 'title', 'text' => 'PRODUCT TITLE']
  ]])


  <div class="col-lg-12 grid-margin stretch-card">
   <div class="card">
    <div class="card-body">
     <table class="table table-hover">
      <thead>
       <tr>
        <th>PRODUCT ID<a href="Javascript:void(0)" title="Click serial to view image"><i class="fa fa-camera text-primary"></i></a></th>
        <th>PRODUCT TITLE</th>
        <th>SERIAL</th>
        <th>CATEGORY</th>
        <th>STATUS</th>
        <th>ACTIONS</th>
        <th>REMOVE PRODUCT</th>
      </tr>
    </thead>
    <tbody>

      @foreach($products as $product)

      <tr>
        <td>
              @include('partials.show-edit-product', ['product_id' => $product->id])
        </td>
        <td>
          <textarea readonly class="form-control">{{$product->title}}</textarea>
        </td>
        <td>
          {{$product->serial}}
        </td>
        <td>
          {{$product->category()->value('name')}}
        </td>
        <td>

         <label class="badge {{$product->status ? 'badge-success' : 'badge-danger'}} custom-min-width-label">{{$product->status ? 'available' : 'unavailable'}}</label>

       <!--<a href="Javascript:void(0)" title="{{$product->status ? 'available' : 'unavailable'}}">
         <i class="fa {{ $product->status ? 'fa-ban text-success' : 'fa-check text-danger'}} "></i></a> -->
       </td>

       <td>
        <ul class="list-group custom-lists-horizontal">
          <li > <a title="edit product" href="{{route('products.edit', $product->id)}}" class="btn social-btn btn-inverse-secondary">
            <i class="fa fa-edit text-black"></i>
          </a>
        </li>
        <li>
          <button type="type" data-toggle="tooltip" title="mark as available" onclick="updateStatus(1, '{{$product->id}}')" class="btn social-btn btn-inverse-secondary">
            <i class="fa fa-check text-black"></i>
          </li>
          <li>
           <a title="mark as unavailable" onclick="updateStatus(0 ,'{{$product->id}}')" class="btn social-btn btn-inverse-secondary">
            <i class="text-black fa fa-ban"></i>
          </a>
        </li>
      </ul>

    </td>
    <td>

      <a onclick="destroyProduct('{{$product->id}}')" title="remove product" class="btn social-btn btn-inverse-secondary">
        <i class="fa fa-trash-o text-black"></i>
      </a>
    </td>
  </tr>

  @endforeach

</tbody>
<tfoot>
  <tr class="custom-pagination-space-around">
    <td><a href="/products/create" class="btn btn-primary btn-fw">Add Product</a></td>
    <td colspan="7">{{$products->links()}}</td> 
  </tr>
</tfoot>
</table>

</div>
</div>
</div>



<script>



  const updateStatus = (value, id) =>{

    if(confirm('Are you sure you want to proceed')) {
     $.ajaxSetup({
      headers: { 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content }
    });

     $.ajax({
      url: "{{url('/products/status')}}",
      method: 'POST',
      data: { 
       status : value,
       id
     },
     success:  res => {
      alert(JSON.stringify(res.success))
      window.location.reload();
    },  
    catch : err => {
     alert(JSON.stringify(err))
   }})
   }

 }
 const destroyProduct = id => {

  if(confirm('Are you sure you want to proceed')) {
   $.ajaxSetup({
    headers: { 'X-CSRF-TOKEN': document.querySelector('meta[name="csrf-token"]').content }
  })
   $.ajax({
    url: '/products/'+id,
    method: 'DELETE',
    data: { 
     id
   },
   success:  res => {
    alert(JSON.stringify(res.success))
    window.location.reload();
  },  
  catch : err => {
   alert(JSON.stringify(err))
 }})
 }

} 


</script>

@endsection

laravel/resources/views/pages/products/show.blade.php
@extends('template.main')


@section('body')

 @include('partials.card-header', ['title' => 'View Product'])

@include('partials.success-error-notification')

<div class="row">
	<div class="col-lg-12 d-flex justify-center ">
		<div class="col-lg-6 grid-margin stretch-card offset-lg-3">
			<div class="card">
				<div class="card-body">

					

						<div class="form-group">
							<label >Product ID</label>
							<input type="text" readonly  value="{{$product->id}}" class="form-control" >
						</div>
						<div class="form-group">
							<label >Product Title</label>
							<input type="text" name="product[title]" class="form-control"  readonly value="{{$product->title}}">
						</div>
						<div class="form-group">
							<label >Product Serial</label>
							<input type="text" class="form-control" name="product[serial]" readonly  value="{{$product->serial}}">
						</div>


						<div class="form-group">
							<label>Status</label>
							<select class="form-control" name="product[status]" disabled>
								@if($product->status)
								<option value="1" selected>Available</option>
								@else
								<option value="0">Not available</option>
								@endif
							</select>
						</div>

						 <div class="form-group">
						 	<label>Initial rate</label>
                          <div class="input-group">
                            <div class="input-group-prepend bg-secondary border-primary">
                              <span class="input-group-text bg-transparent text-black">P</span>
                            </div>
                            <input type="text" class="form-control" readonly value="{{$product->initial_rate}}" name="product[initial_rate]" aria-label="Amount (to the nearest dollar)">
                          </div>
                        </div>


						<div class="form-group">
							<label>Succeeding Days Rate</label>
							<div class="input-group">
								<div class="input-group-prepend bg-secondary border-primary">
									<span class="input-group-text bg-transparent text-black">P</span>
								</div>
								<input readonly type="text" class="form-control"  name="product[succeeding_days_rate]"
								value="{{$product->succeeding_days_rate}}"
								 aria-label="Amount (to the nearest dollar)">
							</div>
						</div>


						<div class="form-group">
							<label>Product Category</label>
							<select class="form-control" name="product[category_id]" disabled  >
								@foreach($categories as $category)

								@if($product->category()->value('id') == $category->id)
								<option value="{{$category->id}}" selected>{{$category->name}}</option>
								@else
								<option value="{{$category->id}}">{{$category->name}}</option>
								@endif

								@endforeach
							</select>
						</div>
						
						<div class="form-group">
							<label>Image</label>
							
							<img id='img-upload' src="{{$product->image_path}}" />
						</div>


						<div class="form-group">
							<label>Notes</label>
							<textarea readonly class="form-control" name="product[notes]" rows="2">{{$product->notes}}</textarea>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>
@endsection